version: '3.8'

services:
  octoprint:
    container_name: octoprint-klipper
    image: octoprint-klipper
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    devices:
      - /dev/my3dprinter:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - octoprint_data:/octoprint
    # - ./octoprint_data:/octoprint
    # - ./octoprint_data/klipper:/octoprint/klipper
    # - ./octoprint_data/plugins:/octoprint/plugins
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -r 1280x720 -f 15
      - TZ=Europe/Lisbon
volumes:
  octoprint_data:
    name: octoprint_data