accessControl:
  userfile: /octoprint/octoprint/users.yaml
server:
  commands:
    serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint && s6-svc -r /var/run/s6/services/klippy
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream
plugins:
  klipper:
    configuration:
      baseconfig: printer.cfg
      config_path: /octoprint/klipper/
      logpath: /octoprint/klipper/klippy.log